name: Test Node SDK
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/node26
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '26.10.0'
          check-latest: true
      - run: npm test
      - run: npm pack --dry-run
